/** Simulated smart-city assets and telemetry for Urban Lens prototype */
window.CITY = {
  districts: [
    { id: "harbor", name: "Harbor Rim", x: 12, y: 58, w: 28, h: 22 },
    { id: "civic", name: "Civic Core", x: 38, y: 30, w: 26, h: 24 },
    { id: "north", name: "North Ridge", x: 62, y: 12, w: 24, h: 26 },
    { id: "garden", name: "Garden Quarters", x: 48, y: 62, w: 30, h: 20 },
  ],
  corridors: [
    { id: "c1", domain: "traffic", d: "M 8 70 C 30 68, 40 50, 52 42 C 64 34, 78 28, 92 22" },
    { id: "c2", domain: "traffic", d: "M 20 20 C 36 36, 44 48, 58 72 C 64 82, 72 86, 88 88" },
    { id: "c3", domain: "energy", d: "M 14 48 C 28 44, 50 40, 70 36 C 80 34, 86 50, 90 64" },
    { id: "c4", domain: "energy", d: "M 40 16 C 48 28, 52 50, 56 78" },
  ],
  assets: [
    {
      id: "sig-01",
      name: "Harbor & 3rd Signal",
      domain: "traffic",
      x: 24,
      y: 66,
      status: "warning",
      hero: { label: "Congestion index", value: 78, unit: "", max: 100 },
      supporting: [
        { label: "Throughput", value: "1.2k", unit: "/h" },
        { label: "Incidents", value: "2", unit: "open" },
      ],
      trend: [42, 48, 55, 61, 70, 74, 78, 76, 78],
      events: [
        { t: "03:12", text: "Queue spillback on west approach" },
        { t: "02:48", text: "Phase timing adjusted (+4s green)" },
        { t: "01:05", text: "Camera feed healthy" },
      ],
    },
    {
      id: "cam-12",
      name: "Civic Plaza Camera",
      domain: "safety",
      x: 50,
      y: 40,
      status: "online",
      hero: { label: "Device health", value: 99, unit: "%", max: 100 },
      supporting: [
        { label: "Open incidents", value: "0", unit: "" },
        { label: "Avg response", value: "4.1", unit: "min" },
      ],
      trend: [97, 98, 98, 99, 99, 99, 98, 99, 99],
      events: [
        { t: "Yesterday", text: "Firmware check OK" },
        { t: "Mon", text: "Lens cleaned (scheduled)" },
      ],
    },
    {
      id: "aqi-07",
      name: "Garden Air Station",
      domain: "environment",
      x: 62,
      y: 72,
      status: "online",
      hero: { label: "AQI", value: 42, unit: "", max: 150 },
      supporting: [
        { label: "PM2.5", value: "12", unit: "µg/m³" },
        { label: "Noise", value: "54", unit: "dB" },
      ],
      trend: [55, 51, 48, 46, 44, 43, 42, 41, 42],
      events: [
        { t: "04:00", text: "Morning dip after wind shift" },
        { t: "22:10", text: "Night baseline restored" },
      ],
    },
    {
      id: "sub-03",
      name: "Ridge Substation",
      domain: "energy",
      x: 74,
      y: 24,
      status: "critical",
      hero: { label: "Load vs capacity", value: 93, unit: "%", max: 100 },
      supporting: [
        { label: "Outage minutes", value: "18", unit: "today" },
        { label: "Renewable share", value: "31", unit: "%" },
      ],
      trend: [68, 72, 75, 80, 84, 88, 91, 93, 93],
      events: [
        { t: "05:41", text: "Transformer T2 thermal warning" },
        { t: "05:20", text: "Load shed recommendation issued" },
        { t: "04:55", text: "Peak ramp began" },
      ],
    },
    {
      id: "ev-04",
      name: "Waterfront EV Hub",
      domain: "energy",
      x: 18,
      y: 62,
      status: "online",
      hero: { label: "Load vs capacity", value: 61, unit: "%", max: 100 },
      supporting: [
        { label: "Active stalls", value: "14/22", unit: "" },
        { label: "Avg session", value: "38", unit: "min" },
      ],
      trend: [40, 44, 48, 52, 58, 60, 61, 59, 61],
      events: [
        { t: "06:02", text: "Two stalls freed" },
        { t: "05:30", text: "Peak commute charging" },
      ],
    },
    {
      id: "lib-01",
      name: "Central Library",
      domain: "civic",
      x: 44,
      y: 36,
      status: "online",
      hero: { label: "Service availability", value: 100, unit: "%", max: 100 },
      supporting: [
        { label: "Queue length", value: "6", unit: "people" },
        { label: "Visits today", value: "840", unit: "" },
      ],
      trend: [20, 35, 55, 70, 85, 90, 95, 98, 100],
      events: [
        { t: "08:00", text: "Doors open — systems green" },
        { t: "Yesterday", text: "HVAC filter replaced" },
      ],
    },
    {
      id: "park-02",
      name: "North Ridge Parking",
      domain: "traffic",
      x: 68,
      y: 18,
      status: "warning",
      hero: { label: "Congestion index", value: 86, unit: "", max: 100 },
      supporting: [
        { label: "Occupancy", value: "91", unit: "%" },
        { label: "Turnover", value: "1.4", unit: "/h" },
      ],
      trend: [60, 68, 74, 80, 84, 87, 86, 88, 86],
      events: [
        { t: "07:15", text: "Lot nearly full" },
        { t: "06:40", text: "Inbound surge from ridge commute" },
      ],
    },
    {
      id: "flood-01",
      name: "Canal Gauge West",
      domain: "environment",
      x: 30,
      y: 78,
      status: "online",
      hero: { label: "AQI", value: 38, unit: "proxy*", max: 150 },
      supporting: [
        { label: "Water level", value: "1.2", unit: "m" },
        { label: "Trend", value: "stable", unit: "" },
      ],
      trend: [40, 39, 39, 38, 38, 37, 38, 38, 38],
      events: [
        { t: "Tide +2h", text: "Within normal band" },
      ],
    },
  ],
};
